### PR TITLE
Added a QueryLogger a la the doctrine/dbal SQLLogger (literally)

### PR DESCRIPTION
**Pull request by AubreyHewes**
### Added a query logger possibility
 Is copied from [doctrine/dbal SQLLogger](http://www.doctrine-project.org/api/dbal/2.5/class-Doctrine.DBAL.Logging.SQLLogger.html) so is more intuitive/recognisable than a bespoke solution.

#### To collect queries and execution time:

    $connector->setQueryLogger(new DebugStack());

Stack is arrays of `$endpoint`, `$params`, `$payload` with timing

#### To just echo the queries during runtime (handy for cli):

    $connector->setQueryLogger(new EchoQueryLogger());

Echoed is `$endpoint`, `$params`, `$payload`

#### Reasoning
The underlying reason was being able to "get" at reliable/realtime stats for use within the kmt-toolbar stats/graphs. 
Though taking a step back and looking at it from a third party pov; the connector should have a debugging/logging possibility.

##### Also the code has been made more reusable 
protected vs private; mockable/testable/etc... ;-)

##### Also the code has been made more readable
moved methods/etc; flow is more kinder to the eye ;-)

##### The core change
For easier readability of this change (as is more than one commit); the main change for this is commit 82a7d0f Thereafter the code has also been made more understandable; there is now just one method (mockable) that executes the request. This is instead of creating a curl handle and later executing the handle. Therefore it is now possible to directly mock the connector.

### CODE REVIEW

**Comment by fruitl00p** [comment]
LGTM Too bad the rearranging of the connector class f*ks with the readability of the diff... But again, LGTM. I like the idea and have wanted it for a while.

@Reggino if say go, lets merge  && :shipit:

**Comment by Reggino** [comment]
go

**Comment by AubreyHewes** [comment]
I would; though there is no release script.. i.e. release to packagist

**Comment by AubreyHewes** [comment]
Readability of the diff was part of pull description; that one commit that was mentiond 82a7d0f was the introduction of the QueryLogger.. The rest of the commits are the readability/testability changes.

**Comment by AubreyHewes** [comment]
I have just merged the latest master back in; due to #13

**Pull request merged**
